### ISSUE TITLE
New SpamAssassin 3.4.3 rules missing

### ISSUE THREAD

**Issue by tajohnson** [spamhaus/spamassassin-dqs#15]
SpamAssassin 3.4.3 adds a couple new rules that need corresponding entries in sh.cf:

RCVD_IN_ZEN_BLOCKED_OPENDNS
RCVD_IN_ZEN_BLOCKED

URIBL_DBL_BLOCKED_OPENDNS
URIBL_DBL_BLOCKED

**Comment by ricalfieri** [comment]
Hi, this has been fixed in the latest commit
