### ISSUE TITLE
Use of uninitialized value in regexp

### ISSUE THREAD

**Issue by xpunkt** [spamhaus/spamassassin-dqs#16]
Use of uninitialized value in regexp compilation at /etc/mail/spamassassin/plugins/SH.pm line 69.

error is not in 3.4.2 it shows up in 3.4.3

**Comment by ricalfieri** [comment]
I'm on 3.4.3 too and I don't see that error. Are you using the latest version?

**Comment by xpunkt** [comment]
yes missed an update, solved by updateing
