### ISSUE TITLE
uri_to_domain" on unblessed reference at /etc/mail/spamassassin/SH.pm line 188

### ISSUE THREAD

**Issue by sasha-** [spamhaus/spamassassin-dqs#17]
SpamAssassin version 3.4.0  running on Perl version 5.16.3

After folllowing instructions to install, this is what shows up in mailog on incomming messages:

Apr 21 16:14:16 example spamd[1764]: spamd: setuid to spamuser succeeded
Apr 21 16:14:16 example spamd[1764]: spamd: processing message <86c628d5-5c16-9f29-733c-e027e9c89633@example.com> for spamuser:1001
Apr 21 16:14:16 example spamd[1764]: rules: failed to run SH_ZRD_HEADERS_VERY_FRESH test, skipping:
Apr 21 16:14:16 example spamd[1764]: (Can't call method "uri_to_domain" on unblessed reference at /etc/mail/spamassassin/SH.pm line 188, <GEN787> line 48.
Apr 21 16:14:16 example spamd[1764]: )
Apr 21 16:14:16 example spamd[1764]: rules: failed to run SH_ZRD_HEADERS_FRESH test, skipping:
Apr 21 16:14:16 example spamd[1764]: (Can't call method "uri_to_domain" on unblessed reference at /etc/mail/spamassassin/SH.pm line 188, <GEN787> line 48.
Apr 21 16:14:16 example spamd[1764]: )
Apr 21 16:14:16 example spamd[1764]: rules: failed to run SH_DBL_HEADERS_ABUSED test, skipping:
Apr 21 16:14:16 example spamd[1764]: (Can't call method "uri_to_domain" on unblessed reference at /etc/mail/spamassassin/SH.pm line 188, <GEN787> line 48.
Apr 21 16:14:16 example spamd[1764]: )
Apr 21 16:14:16 example spamd[1764]: rules: failed to run SH_DBL_HEADERS test, skipping:
Apr 21 16:14:16 example spamd[1764]: (Can't call method "uri_to_domain" on unblessed reference at /etc/mail/spamassassin/SH.pm line 188, <GEN787> line 48.
Apr 21 16:14:16 example spamd[1764]: )
Apr 21 16:14:16 example spamd[1764]: rules: __RCVD_IN_ZEN_LASTEXTERNAL took 0.0621111392974854 seconds to complete, for RCVD_IN_ZEN_LASTEXTERNAL
Apr 21 16:14:17 example spamd[1764]: spamd: clean message (-1.2/5.0) for spamuser:1001 in 1.3 seconds, 2175 bytes.

**Comment by ricalfieri** [comment]
Hi,
SpamAssassin 3.4.0 is unfortunately not supported, sorry. Minimum version is 3.4.1 but we always recommend the latest

**Comment by sasha-** [comment]
Thanks. Upgrading to 3.4.4 fixed this.
