### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by heutger** [spamhaus/spamassassin-dqs#19]
Hi,

thanks for your effort and the installation guide. I just wonder, why you use sed to place the key but placing the path is been done via editor? Why don't you use sed there also?

Regards
Christian

**Comment by ricalfieri** [comment]
Hi,

uhm.. I guess it's up to anyone to use whatever tool they are comfortable with :) It was probably something I overlooked when writing the instructions, but I don't think it's a show stopper

**Comment by heutger** [comment]
Hi,

sure it isn’t, however it’s much easier to sed something and to follow such intruction by copy and paste than doing a file edit by yourself like with vi.

Regards
Christian

**Comment by ricalfieri** [comment]
Sensible pull requests are always welcome :)
