### ISSUE TITLE
Unnecessary List::MoreUtils

### ISSUE THREAD

**Issue by hekeli** [spamhaus/spamassassin-dqs#2]
I suggest removing the completely unnecessary and superficial dependency of List::MoreUtils, and instead use the "ancient" method of hashing:

my %emails;
while (...) { ... $emails{$foo} = 1; ... }
my @uniq_emails = keys %emails;

**Comment by ricalfieri** [comment]
Would you mind submitting a patch or a merge request?

**Comment by hekeli** [comment]
I leave this up to you since it's trivial really, I try to direct my free hobby work time directly into SpamAssassin.

**Comment by ricalfieri** [comment]
Done, prerequisite removed
