### ISSUE TITLE
Syntax error on SH.pm

### ISSUE THREAD

**Issue by castrelo02** [spamhaus/spamassassin-dqs#20]
When I check the spamassassin syntax it returns an error
It seems that the module has some syntax error

**Error**
```
# spamassassin --lint
May 20 20:55:56.416 [27490] warn: plugin: failed to parse plugin /usr/share/spamassassin/rules/plugins/SH.pm: Missing right curly or square bracket at /usr/share/spamassassin/rules/plugins/SH.pm line 829, at end of line
May 20 20:55:56.416 [27490] warn: syntax error at /usr/share/spamassassin/rules/plugins/SH.pm line 829, at EOF
May 20 20:55:56.416 [27490] warn: Compilation failed in require at /usr/share/perl5/Mail/SpamAssassin/PluginHandler.pm line 119.
```

**Versions**
```
SpamAssassin version 3.4.2
Perl version 5.24.1
```

**Comment by ricalfieri** [comment]
I'm not able to reproduce the error. Did you download the latest version?

**Comment by udf2457** [comment]
I also have not seen the error (Debian 10, a.ka. SpamAssassin version 3.4.2, running on Perl version 5.28.1).  My `spamassassin lint` returns no errors.

Are you sure you're putting the plugins in the right place ?  `/usr/share` seems a bit odd ?  On Debian they live in `/etc/spamassassin`

**Comment by castrelo02** [comment]
oh I'm sorry
I had wrongly copied the SH.pm module and it had an error in the syntax

It's working fine for me, thanks
