### ISSUE TITLE
Readme section on scoring

### ISSUE THREAD

**Issue by udf2457** [spamhaus/spamassassin-dqs#21]
Thank you for this great tool to improve SA.

However I have one little request, you state:

> The scores in this configuration file are weighted for a required_score of 4 instead of the default 6. If you use a different required_score, remember to adjust the values accordingly.

It would, perhaps, be useful to hint at what scores you think are worthy of consideration for adjustment and what scores should really be left untouched ierrespective of `required_score`.

**Comment by ricalfieri** [comment]
thanks for spotting, fixed

**Comment by ricalfieri** [comment]
Hello,

apologies for the delay. With the just released version 1.1.1 I "fixed" this problem and rescored some rules to properly work with the default required_score of 5.
