### ISSUE TITLE
reusing last domain

### ISSUE THREAD

**Issue by amoi69** [spamhaus/spamassassin-dqs#24]
When using SA-DQS, sometimes (not all the time), the plugin is using the previous domain name to search, not the one from the current email coming in.
I will try to explain, a 1st email is coming in from smtp.onedomain.com and the SA-DQS is processing it.
Then a second email is coming in later on from smtp2.seconddomain.com; and here the SA-DQS is processing it but in the log I am seeing it using dns search for smtp.onedomain.com and not smtp2.seconddomain.com.

I am adding a text copy of mu logs for better understanding.

Thank you for your support.
[DQS-SA.txt](https://github.com/spamhaus/spamassassin-dqs/files/4890396/DQS-SA.txt)

**Comment by ricalfieri** [comment]
Hi,

this is very unlikely to be a bug of the plugin. What happens if you save an email and then run

spamassassin -D < email.eml

?

**Comment by amoi69** [comment]
Hi,

When I parsing an email in SpamAssassin in Debug mode as you recommended, everything is OK.
I will try to understand what is going on but I am still seeing the issue, I do not know if postfix, SpamAssassin or plugin is not initialized between each email so the last DNS is staying in.

Thank you for your support.

**Comment by ricalfieri** [comment]
It really depends on how your whole infrastructure work together. If manually running the check doesn't trigger the error then probably is something you have to look for in the rest of your email delivery pipeline

Sorry for not being able to help more :)
