### ISSUE TITLE
Problem with shortcircuit 

### ISSUE THREAD

**Issue by Caez83** [spamhaus/spamassassin-dqs#26]
Hello, 

I have problem with the shortcircuit option added on sh.pre option 
The option override trusted_network list and add 100 point to the mail

In my conf mail with a score > 100 are dropped
Why are you using this option ?

**Comment by ricalfieri** [comment]
Shortcircuit doesn't override trusted_networks.

Anyway it is used because if a connecting IP is listed in ZEN, there is almost 0 chance that it could be a legitimate email, and it is shortcircuited to avoid processing further rules, keeping the CPU load lighter

**Comment by Caez83** [comment]
We've receveing a lot of mail from mailinblack service, a mail protection system and these IP appear reguliarly in Spamhauss Zen.
We've whitlisted it in our trusted_networks blocks but the shortcircuit option add 100 to the mail even if they're in trusted_net
