### ISSUE TITLE
VirusBulletin VBspam URL in README no good.  

### ISSUE THREAD

**Issue by elvey** [spamhaus/spamassassin-dqs#27]
The README links to 
https://www.virusbulletin.com/testing/results/latest/vbspam-email-security which doesn't currently mention Spamhaus DQS.  

What to do?  It seems that DQS is mentioned _on and off_ at the latest results URL currently in the README. It IS mentioned in these two places, but they'll get old:
https://www.virusbulletin.com/virusbulletin/2020/09/vbspam-comparative-review#h3-spamhaus-data-query-service
https://www.virusbulletin.com/virusbulletin/2020/06/vbspam-comparative-review#h3-spamhaus-data-query-service

https://www.virusbulletin.com/testing/vbspam/ should stay current, at least.

Maybe https://www.virusbulletin.com/testing/results/compare/vbspam-email-security/spamhaus-dqs__vs__spamhaus-rsync/in-last-10-tests is best; it compares Spamhaus DQS alone to Spamhaus rsync alone, and does show DQS is better, which fits perfectly with what the URL is there for, in context.

Not sure what editing would be best.

**Comment by ricalfieri** [comment]
DQS is mentioned in https://www.virusbulletin.com/testing/results/latest/vbspam-email-security

It's just above ZEROSPAM (the list is alphabetically ordered)

**Comment by elvey** [comment]
So it is.  Sorry.

FYI, I was thrown by the invisibility of the two scrolling areas on the page being hidden by MacOS' UI hiding the scrollbars. So Couldn't see the entries. Certainly not a bug in DQS!
(In System Preferences...General...Show scroll bars doesn't default to Always and I'm not using my usual Mac login that has it set to always.)
