### ISSUE TITLE
getting "Use of uninitialized value in concatenation" error

### ISSUE THREAD

**Issue by UnP1u9** [spamhaus/spamassassin-dqs#32]
Hi Team, I was configuring Spamhaus with SpamAssassin version 3.4.4 and started getting bellow error, previously is was working fine, just started to get this error today.

Jan 29 07:37:54.893 [5433] warn: Use of uninitialized value in concatenation (.) or string at /etc/mail/spamassassin/SH.pm line 824.
Jan 29 07:37:54.894 [5433] warn: Use of uninitialized value in concatenation (.) or string at /etc/mail/spamassassin/SH.pm line 824.
Jan 29 07:37:54.953 [5433] warn: Use of uninitialized value in concatenation (.) or string at /etc/mail/spamassassin/SH.pm line 824.

Thanks.

**Comment by ricalfieri** [comment]
I can't reproduce the error with SA 3.4.4. Are you sure you are using the latest version of the plugin? Did this error happen while doing a --lint?

**Comment by UnP1u9** [comment]
Hi, I was getting this on debug mode, reinstalled SpamAssassin and it is working fine now.

Thanks
