### ISSUE TITLE
Improve email parser

### ISSUE THREAD

**Issue by hekeli** [spamhaus/spamassassin-dqs#4]
Seems _get_domains_from_body_emails doesn't check uri_to_domain result to skip obviously invalid tlds/domains.

Also it's always bad idea to use unlimited ([foo]+)+ like matching:
\b([\w\d\_\-\+\.]+\@(?:[\w\d\-]+\.)+[\w\d\-]{2,10})\b/g
Easy improvement would be limiting username, hostname component length and counts. Also could check valid tlds directly in the regex (see SpamAssassin FreeMail.pm / HashBL.pm).

**Comment by ricalfieri** [comment]
Thanks for the suggestion, I replaced my code with some taken from HashBL
