### ISSUE TITLE
score of SH_ZRD_BODY_VERY_FRESH 

### ISSUE THREAD

**Issue by jpopovitch** [spamhaus/spamassassin-dqs#40]
Is it an oversight that there is no score in sh_scores.cf for SH_ZRD_BODY_VERY_FRESH, or is it expected that end-users should maintain that score?  Thanks!!

**Comment by ricalfieri** [comment]
Thanks for noticing. I also missed to add scores for SH_ZRD_BODY_FRESH

They are now both added to sh_scores.cf
