### ISSUE TITLE
What's the plan with the dbl-beta tree ?

### ISSUE THREAD

**Issue by udf2457** [spamhaus/spamassassin-dqs#42]
Not an issue per-se but more something that requires clarifications.

I've received a number of emails from Spamhaus promoting the new enhancements to DQS.  Which is great.

What is not clear, however is what's going to happen  with the dbl-beta tree ?

My update processes are currently following the master tree, I would rather not switch to dbl-beta if the dbl-beta changes are going to be merged to master on 1st Feb ?  Or is it expected that the user-base switches to dbl-beta tree ?

The Spamhaus mailings are unclear in this respect.

**Comment by ricalfieri** [comment]
Hello,

the dbl-beta tree will be merged to master on Feb 1

**Comment by udf2457** [comment]
Super thanks !
