### ISSUE TITLE
SA warnings

### ISSUE THREAD

**Issue by birkosan** [spamhaus/spamassassin-dqs#44]
Hi,
With the dqs plugin enabled I get the following warnings in the log:

SA info: async: bgsend_and_start_lookup called without rulename: xxxxxxxxx.xxx/A
_WARN: Use of uninitialized value $rulename in hash element at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/AsyncLoop.pm line 268.

Spamassassin is called from amavisd-new

Please ask if you need any additional information
Thanks

**Comment by birkosan** [comment]
Plugin is the latest from github.

# spamassassin -V
SpamAssassin version 4.0.0-r1889518
  running on Perl version 5.16.3

Basically every mail fires that with an URL in the body.

Thanks

**Comment by ricalfieri** [comment]
I see, you are using SA 4.0 that is not officially released yet. We are waiting for the official release to port our plugin to that version. As soon the project release the first stable version it will be one of my primary task to iron out every bug

**Comment by birkosan** [comment]
OK, thanks!
