### ISSUE TITLE
Helo checks problem

### ISSUE THREAD

**Issue by mdvtr** [spamhaus/spamassassin-dqs#45]
Hi all!
I am using Proxmox Mail Gateway, installed the SH plugin, but when I testing config via BLT get the problem with SMTP HELO, what could be the problem?
![12](https://user-images.githubusercontent.com/56835123/152951490-fec5bf66-54b6-45f4-88a6-e3b3ae1bff20.JPG)
![изображение](https://user-images.githubusercontent.com/56835123/152951716-f7988669-e01e-45f6-9803-5a063be831a7.png)
![изображение](https://user-images.githubusercontent.com/56835123/152952264-59b9d0df-516c-46cf-9c04-40721f1d961c.png)

**Comment by ricalfieri** [comment]
Hi,

unfortunately I'm not familiar with Proxmox Mail Gateway. In any case, you should check the headers of the email you received and that are marked as "delivered" by BLT. If you correctly installed the SA plugin they should have the "X-Spam-Flag" set to "Yes". If that's the case then the test should be considered as passed, see the section "test Emails" on https://blt.spamhaus.com/docs
