### ISSUE TITLE
Regular expressions without '$'?

### ISSUE THREAD

**Issue by robert-scheck** [spamhaus/spamassassin-dqs#46]
Is it really intended that the following regular expressions are without a terminating `$`?

https://github.com/spamhaus/spamassassin-dqs/blob/4d086846defc10f6535f9b656274a139cbe0126e/sh.cf#L73
https://github.com/spamhaus/spamassassin-dqs/blob/4d086846defc10f6535f9b656274a139cbe0126e/sh.cf#L77
https://github.com/spamhaus/spamassassin-dqs/blob/4d086846defc10f6535f9b656274a139cbe0126e/sh.cf#L81
https://github.com/spamhaus/spamassassin-dqs/blob/4d086846defc10f6535f9b656274a139cbe0126e/sh.cf#L85

As of writing, not only a returned `127.0.0.2` would be matched by the first expression, but also e.g. a returned `127.0.0.255`. And even if that behaviour is intended, all other rules do handle possible replies explicitly rather implicitly.

**Comment by ricalfieri** [comment]
You are correct and those regexes are now fixed
