### ISSUE TITLE
Clarification of setup instructions using sed(1)?

### ISSUE THREAD

**Issue by robert-scheck** [spamhaus/spamassassin-dqs#47]
Based on https://bugzilla.redhat.com/show_bug.cgi?id=2048938#c9, I wonder if the setup instructions in `README.md` can be somehow clarified regarding the `sed` usage?

Alternatively, I could imagine to write a Fedora/RHEL-specific small setup script that tests the given DQS key and performs the replacements (and also handles HBL). As longer as I'm thinking about, a small setup script could be helpful and solve #39 in another way. Please let me know your thoughts as upstream, too :)

**Comment by ricalfieri** [comment]
Hi Robert,

I'm not sure I understand the problem. The sh.cf file that is present in this repository is correct and the sed command works on it. Maybe you are changing it when you build your package?

Also, about the setup script, you are welcome to write something for Fedora/RH! I don't have those distrubtions handy and, more imprtantly, I'm not familiar with the build process for RPM packages :) If you create something that "just works" (TM) and give me detailed instructions on how to install it I'll be glad to add a mention to the README file
