### ISSUE TITLE
use drill install of dig

### ISSUE THREAD

**Issue by HLFH** [spamhaus/spamassassin-dqs#48]
Hi,

I recommend the use of drill install of dig in hbltest.sh.
See: https://archlinux.org/todo/dnsutils-to-ldns-migration/

**Comment by udf2457** [comment]
FWIW, I disagree.  This whole `drill` thing sounds like a very archlinux specific thing. 

Debian and everyone else are still very much using `dig` nine years after archlinux moved to `drill`, so I'd say `dig` is here to stay for the foreseeable future.

**Comment by ricalfieri** [comment]
> FWIW, I disagree. This whole `drill` thing sounds like a very archlinux specific thing.
> 
> Debian and everyone else are still very much using `dig` nine years after archlinux moved to `drill`, so I'd say `dig` is here to stay for the foreseeable future.

I'm with you on this
