### ISSUE TITLE
I've made a FreeBSD port...

### ISSUE THREAD

**Issue by lrosenman** [spamhaus/spamassassin-dqs#5]
So the install for FreeBSD is to:

pkg install spamassassin-dqs

and follow the instructions, or if using ports:

cd /usr/ports/mail/spamassassin-dqs
sudo make install

I'll keep it up to date with your tags (I'm following the repo).

this is available in r505848 of the ports tree or later.

**Comment by ricalfieri** [comment]
Thanks!
I added a reference in the documentation
