### ISSUE TITLE
Plugin is not compatible with SpamAssassin 4.0.0

### ISSUE THREAD

**Issue by tajohnson** [spamhaus/spamassassin-dqs#52]
SpamAssassin 4.0.0 Release Candidate 1 is available now:

https://lists.apache.org/thread/cqhpzy9pp26mq7bzw4jcvzx6swop6lcg

But the SH.pm plugin is not compatible 

`Sep  8 18:08:20.569 [28077] warn: async: bgsend_and_start_lookup called without rulename, from Mail::SpamAssassin::Plugin::SH (/etc/mail/spamassassin/plugins/SH.pm) line 843. You are likely using a plugin that is not compatible with SpamAssasin 4.0.0.....`

**Comment by jpopovitch** [comment]
Seeing the same errors now on a debian bookworm host:

```
Sep 14 18:40:44 mx3 spamd[1445]: async: bgsend_and_start_lookup called without rulename, from Mail::SpamAssassin::Plugin::SH (/etc/spamassassin/SH.pm) line 843. You are likely using a plugin that is not compatible with SpamAssasin 4.0.0. at /usr/share/perl5/Mail/SpamAssassin/AsyncLoop.pm line 219, <GEN12> line 97.
```

**Comment by RvdHout** [comment]
4.0.0 is officially out now

**Comment by ricalfieri** [comment]
Rules for 4.0.x will be published before the end of the year
