### ISSUE TITLE
Followed instructions, but Postfix continues to reject all mail

### ISSUE THREAD

**Issue by sanctimon** [spamhaus/spamassassin-dqs#53]
Hello,

I started getting the Spamhaus error on 29 Oct 2022 and since then, no emails are received with the following error:

`Oct 31 01:28:43 mail postfix/smtpd[3468]: NOQUEUE: reject: RCPT from mail-lo2gbr01olkn0166.outbound.protection.outlook.com[104.47.21.166]: 554 5.7.1 Service unavailable; Client host [104.47.21.166] blocked using sbl.spamhaus.org; Error: open resolver; https://www.spamhaus.org/returnc/pub/172.69.79.93; from=<xxxxx@xxxx.xxx> to=<xxxxx@xxxxx.xxx> proto=ESMTP helo=<GBR01-LO2-obe.outbound.protection.outlook.com>`

I followed the instructions provided to the letter and applied all four files (I do not have the HBL service yet) to the /etc/mail/spamassassin folder.

I have also set up a local dns cache (dnsmasq) and forced my raspbian server to look at 127.0.0.1 for its DNS queries rather than address them to CloudFlare.

I have restarted all services and the error above persists. Any help would be appreciated.

**Comment by ricalfieri** [comment]
This is not related to the plugin but to POstifx configuration. You neel to replace blocklist lookups also in /etc/postfix/main.cf
