### ISSUE TITLE
BLT DQS Content Test Email Issue

### ISSUE THREAD

**Issue by dominicraf** [spamhaus/spamassassin-dqs#57]
Not an issue with what is here as such, but the system that allows testing of configuration seems to me to be wrongly configured for the content tests, as a result none of them work properly:

1. zrd-dqs-body-domain - presumably an attempt to trigger SH_ZRD_BODY_VERY_FRESH but it does so using body text that includes a bad *http address*, whereas that test (and SH_ZRD_BODY_FRESH) are only for bad *email addresses* within body text, so they never trigger
2. dbl-dqs-body-domain - as above but presumably for SH_DBL_BODY and/or SH_DBL_BODY_ABUSED, same problem applies
3. sbl-dqs-body-ip - presumably an attempt to trigger SH_BODYURI_REVERSE_SBL but it does so using an http ip-based address, whereas that test is against the A record of URIs in the body text

**Comment by ricalfieri** [comment]
Hi, I did some tests and

zrd-dqs-body-domain correctly triggers URIBL_ZRD

dbl-dqs-body-domain triggers URIBL_DBL_SPAM 

sbl-dqs-body-ip triggers URIBL_SBL

This on a vanilla SA installation with just the plugin installed and configured
