### ISSUE TITLE
Is SH.pm needed is spamassassin 4.0?

### ISSUE THREAD

**Issue by willt** [spamhaus/spamassassin-dqs#59]
I don't see SH.pm in the 4.0 dqs files.
I tried using the 4.0.0+/*.cf files without the plugin in 3.4.1+/SH.pm but it gave me an error about an unknown eval check check_hashbl_emails

 spamassassin --lint
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_ZRD_HEADERS_FRESH
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_DBL_BODY
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_REVERSE_ZRD_VERY_FRESH
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_HBL_EMAILS_GMAIL
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_REVERSE_DBL
Jun 13 11:58:38.100 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_ZRD_HEADERS_VERY_FRESH
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_DBL_HEADERS
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_HBL_EMAILS
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_HELO_DBL
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_HELO_ZRD_FRESH
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_ZRD_BODY_FRESH
Jun 13 11:58:38.102 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_HELO_ZRD_VERY_FRESH
Jun 13 11:58:38.103 [248577] warn: rules: unknown eval 'check_hashbl_emails' for SH_ZRD_BODY_VERY_FRESH
Jun 13 11:58:38.103 [248577] warn: rules: unknown eval 'check_hashbl_tag' for SH_REVERSE_ZRD_FRESH
Jun 13 11:58:38.104 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_ETH
Jun 13 11:58:38.104 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_BTC
Jun 13 11:58:38.104 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_LTC
Jun 13 11:58:38.104 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_XRP
Jun 13 11:58:38.105 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_XMR
Jun 13 11:58:38.105 [248577] warn: rules: unknown eval 'check_hashbl_bodyre' for SH_HBL_CW_BCH
Jun 13 11:58:38.399 [248577] warn: rules: unknown eval 'check_hashbl_attachments' for SH_HBL_FILE_SUSPICIOUS
Jun 13 11:58:38.400 [248577] warn: rules: unknown eval 'check_hashbl_attachments' for SH_HBL_FILE_MALWARE
Jun 13 11:58:38.925 [248577] warn: lint: 22 issues detected, please rerun with debug enabled for more information

I'm asking here because the instructions don't mention installing the plugin which seems weird but if it's all built in to spamassassin now that would make sense.
Currently I'm using the 3.4.1+ files with Spamassassin 4.0 and it appears to be working.

**Comment by willt** [comment]
Looks like I need this plugin loaded. This should probably be in the instructions.
grep Mail::SpamAssassin::Plugin::HashBL *
v342.pre:# loadplugin Mail::SpamAssassin::Plugin::HashBL

**Comment by ricalfieri** [comment]
Isn't HashBL.pm loaded by default in 4.0.x? It is in my installation

**Comment by willt** [comment]
> Isn't HashBL.pm loaded by default in 4.0.x? It is in my installation

Maybe in a new installation? This was an upgrade. The only thing that loads HashBL.pm I saw was in the v342.pre file and in version 3.4.2 it was commented out by default so it hasn't been enabled by default for some time.

**Comment by ricalfieri** [comment]
I'll update the 4.0.0+ branch with a sh.pre that will load HashBL

**Comment by RvdHout** [comment]
Is it me or did you somehow create a bit of a mess with 1.5.0 release package? The release tag package still hasn't got the sh.pre in /4.0.0+ folder as you stated

If you download the 'master', it has sh.pre inside /4.0.0+, but also SH.pm which isn't needed on 4.0.0+ and is solely needed for 3.4.1+?

**Comment by willt** [comment]
Pretty sure SH.pm in 4.0.0+ folder has all the old unneeded bits stripped out and is just for hbl now.

**Comment by RvdHout** [comment]
Yeah but that is exactly what is wrong with the recently 1.5.0 package, it is not in https://github.com/spamhaus/spamassassin-dqs/releases/tag/v1.5.0

**Comment by willt** [comment]
ah yeah I see. That is a problem.

**Comment by ricalfieri** [comment]
I tagged 1.5.1 and looks like it has all needed files. Thanks
