### ISSUE TITLE
code needs to strip ending dots of dns values

### ISSUE THREAD

**Issue by jhaar** [spamhaus/spamassassin-dqs#6]
I just installed spamassassin-dqs and the very first spam email I pushed through generated an error.

Jul  6 15:02:11.851 [29954] warn: dns: new_dns_packet (domain=ec2-54-249-116-194.ap-northeast-1.compute.amazonaws.com..XXXXXXXX.zrd.dq.spamhaus.net. type=A class=IN) failed: a domain name contains a null label

The reason is this line from the email: you will see the dns name ends in a dot (which is valid BTW)

Received: from mvc.ajdmsdrab.com (ec2-54-249-116-194.ap-northeast-1.compute.amazonaws.com. [54.249.116.194])

I'd guess your parser needs changing to strip off ending dots?

Thanks

Jason

**Comment by ricalfieri** [comment]
Thanks for spotting that, out of curiosity, what MTA are you using?

Anyway, I believe this comes from the function check_sh_reverse. I now added a check for eventual trailing dots.

Let me know if it solves the problem for you

**Comment by jhaar** [comment]
old school - qmail-scanner in front of qmail :-)

**Comment by ricalfieri** [comment]
good, I'm tagging a new relese :)
