### ISSUE TITLE
Removal of URIBL_ZRD from 3.4.1+

### ISSUE THREAD

**Issue by robert-scheck** [spamhaus/spamassassin-dqs#62]
Commit 203bfa250a84ecc5f80c9a5d59cde704b57b27a9 removed `URIBL_ZRD` from `3.4.1+/sh_scores.cf` – why is that?

In difference, at `4.0.0+/sh_scores.cf` only `SH_ZRD_BODY` was removed, not `URIBL_ZRD`; this feels quite inconsistent.

**Comment by robertmathews** [comment]
I was wondering the same thing -- the `URIBL_ZRD` check is still done in `sh.cf`, but it no longer has any score. Is that intentional?

**Comment by ariabamdad** [comment]
I have had this problem and finally saw this report.  No score is applied to this test in 3.4.1+/sh_scores.cf.  Can you clarify if this was intentional and why?

**Comment by xrat** [comment]
So this is also why BLT DQS Content Test fails.

**Comment by ricalfieri** [comment]
I did some changes, can you check if they are ok?

**Comment by xrat** [comment]
The Content test via https://blt.spamhaus.com/ worked now for me. Thanks!

**Comment by ariabamdad** [comment]
Hi. I did a quick comparison of the code and found that this: "score       SH_ZRD_BODY             6" was added to the sh_scores.cf file for 3.4.1+.  Is this the only change made?  I had added this line to my local.cf file to address the problem, but if this was the only change, I will upgrade to the latest version and remove that line. 

Thank you for addressing this quickly.

**Comment by ricalfieri** [comment]
There was something broken also in 4.0.x so i fixed that in both places. Closing this issue
