### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by Pascal76** [spamhaus/spamassassin-dqs#66]
Hello,
For the installation, maybe you could add to do a chmod 644 ?

**Comment by ricalfieri** [comment]
are you talking about the hbltest script?

**Comment by Pascal76** [comment]
no

**Comment by ricalfieri** [comment]
expand your issue and provide an example

**Comment by Pascal76** [comment]
unzip master.zip

ls -alth spamassassin-dqs-master/3.4.1+/

drwxr-x--- 2 root root  125  5 janv. 10:32 .
drwxr-x--- 4 root root  118  5 janv. 10:32 ..
-rwxr-xr-x 1 root root  700  5 janv. 10:32 hbltest.sh
-rw-r----- 1 root root  11K  5 janv. 10:32 sh.cf
-rw-r----- 1 root root 5,0K  5 janv. 10:32 sh_hbl.cf
-rw-r----- 1 root root  632  5 janv. 10:32 sh_hbl_scores.cf
-rw-r----- 1 root root  44K  5 janv. 10:32 SH.pm
-rw-r----- 1 root root  319  5 janv. 10:32 sh.pre
-rw-r----- 1 root root 1,7K  5 janv. 10:32 sh_scores.cf

(
umask
27
)

**Comment by ricalfieri** [comment]
that depends on your umask, it's not an issue of this package
