### ISSUE TITLE
how to disable spamhaus checks

### ISSUE THREAD

**Issue by Pascal76** [spamhaus/spamassassin-dqs#67]
I would like to disable spamhaus rbl checks but I don't know how to do.

I added some lines in /etc/mail/spamassassin/local.cf
score __RCVD_IN_ZEN 0
score RCVD_IN_SBL 0
score RCVD_IN_XBL 0
score RCVD_IN_PBL 0
score URIBL_SBL 0
but it does not work :(

**Comment by ricalfieri** [comment]
It's probably because the plugin files get processed after local.cf. However, this is not a question for this repository, if you need help with spamassassin, ask on spamassassin-users
